const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
export class AudioAnalyzer {
  constructor(){ this.bpm=124;this.targetBpm=124;this.confidence=0;this.features={rms:0,bass:0,mid:0,high:0,onset:0};this.onsets=[];this.energyHistory=[];this.lastOnset=0;this.lastUpdate=0;this.phase=0;this.beats=0; }
  async start(){ try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});this.ctx=new AudioContext();const source=this.ctx.createMediaStreamSource(stream);this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=2048;this.analyser.smoothingTimeConstant=.35;source.connect(this.analyser);this.freq=new Uint8Array(this.analyser.frequencyBinCount);this.time=new Uint8Array(this.analyser.fftSize);return true}catch(e){console.warn('Microphone unavailable',e);return false} }
  band(from,to){let sum=0;for(let i=from;i<to;i++)sum+=this.freq[i]||0;return sum/Math.max(1,to-from)/255}
  updateClock(now,target){if(!this.lastUpdate){this.lastUpdate=now;return}const dt=Math.min(100,now-this.lastUpdate);this.lastUpdate=now;this.bpm+=(target-this.bpm)*Math.min(1,dt/900);const advance=dt*this.bpm/60000;this.phase=(this.phase+advance)%1;this.beats+=advance}
  estimateTempo(now){const recent=this.onsets.filter(t=>now-t<10000);if(recent.length<5)return;const scores=[];for(let bpm=70;bpm<=180;bpm++){const period=60000/bpm;let score=0;for(let i=1;i<recent.length;i++)for(let j=0;j<i;j++){const gap=recent[i]-recent[j],multiple=Math.round(gap/period);if(multiple>=1&&multiple<=16)score+=Math.exp(-Math.pow((gap-multiple*period)/(period*.11),2))}scores.push({bpm,score})}scores.sort((a,b)=>b.score-a.score);const best=scores[0],second=scores[1]||{score:0},confidence=best.score?clamp((best.score-second.score+best.score*.15)/(best.score+1),0,1):0;const variants=[best.bpm,best.bpm/2,best.bpm*2].filter(v=>v>=70&&v<=180);const chosen=variants.reduce((a,b)=>Math.abs(b-this.bpm)<Math.abs(a-this.bpm)?b:a);this.confidence=this.confidence*.8+confidence*.2;if(this.confidence>.22)this.targetBpm=chosen}
  update(now,auto){if(!this.analyser){this.updateClock(now,this.bpm);return this.features}this.analyser.getByteFrequencyData(this.freq);this.analyser.getByteTimeDomainData(this.time);let rms=0;for(const v of this.time)rms+=((v-128)/128)**2;rms=Math.sqrt(rms/this.time.length);const bass=this.band(2,28),mid=this.band(28,150),high=this.band(150,360),energy=bass*.72+mid*.28,mean=this.energyHistory.length?this.energyHistory.reduce((a,b)=>a+b,0)/this.energyHistory.length:energy;this.energyHistory.push(energy);while(this.energyHistory.length>43)this.energyHistory.shift();const onset=Math.max(0,energy-mean);this.features={rms,bass,mid,high,onset};if(auto&&onset>Math.max(.018,mean*.17)&&now-this.lastOnset>180){this.onsets.push(now);this.onsets=this.onsets.filter(t=>now-t<10000);this.lastOnset=now;this.estimateTempo(now)}this.updateClock(now,auto?this.targetBpm:this.bpm);return this.features}
  setManualBpm(bpm){this.targetBpm=clamp(bpm,60,180);this.confidence=1}
  clock(){return {phase:this.phase,beats:this.beats,bpm:this.bpm}}
}
