import {PoseTracker} from './pose.js';import {AudioAnalyzer} from './audio.js';import {PerformanceController} from './performance.js';import {dancePose,blend} from './dance.js';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('canvas'),ctx=canvas.getContext('2d'),tracker=new PoseTracker(),audio=new AudioAnalyzer(),performanceCtl=new PerformanceController();
let faces=[],pose=null,lastPose=null,started=false,lastFrame=0,fps=0,trail=[];
const settings=()=>({line:+$('line').value,intensity:+$('intensity').value,reactivity:+$('reactivity').value,distance:+$('distance').value,genre:$('genre').value,mirror:$('mirror').checked,display:$('display').value,faceScale:+$('faceScale').value,faceX:+$('faceX').value,faceY:+$('faceY').value});
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();
function fallback(w,h,t){let s=Math.min(w,h)*.18,cx=w/2,cy=h*.55,b=Math.sin(t/440);let j={shoulderL:{x:cx-s*.55,y:cy-s},shoulderR:{x:cx+s*.55,y:cy-s},elbowL:{x:cx-s*.9,y:cy-s*.45+b*s*.2},elbowR:{x:cx+s*.9,y:cy-s*.45-b*s*.2},wristL:{x:cx-s*1.1,y:cy-s*.1},wristR:{x:cx+s*1.1,y:cy-s*.1},hipL:{x:cx-s*.38,y:cy},hipR:{x:cx+s*.38,y:cy},kneeL:{x:cx-s*.45,y:cy+s},kneeR:{x:cx+s*.45,y:cy+s},ankleL:{x:cx-s*.55,y:cy+s*1.8},ankleR:{x:cx+s*.55,y:cy+s*1.8}};return {joints:j,cx,cy,scale:s,head:{x:cx,y:cy-s*1.7}}}
const edge=[['shoulderL','shoulderR'],['shoulderL','elbowL'],['elbowL','wristL'],['shoulderR','elbowR'],['elbowR','wristR'],['shoulderL','hipL'],['shoulderR','hipR'],['hipL','hipR'],['hipL','kneeL'],['kneeL','ankleL'],['hipR','kneeR'],['kneeR','ankleR']];
function draw(p,alpha=1){let s=settings(),j=p.joints;ctx.save();ctx.globalAlpha=alpha;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#d1ff45';ctx.shadowBlur=18;ctx.shadowColor='#aaff00';ctx.lineWidth=s.line;for(const[a,b]of edge){ctx.beginPath();ctx.moveTo(j[a].x,j[a].y);ctx.lineTo(j[b].x,j[b].y);ctx.stroke()}ctx.shadowBlur=0;ctx.fillStyle='#fff';for(const q of Object.values(j)){ctx.beginPath();ctx.arc(q.x,q.y,Math.max(2,s.line*.45),0,7);ctx.fill()}let face=faces[+$('faceSelect').value];let hs=p.scale*.72*s.faceScale,x=p.head.x+s.faceX,y=p.head.y+s.faceY;if(face){ctx.save();ctx.translate(x,y);ctx.drawImage(face,-hs,-hs,hs*2,hs*2);ctx.restore()}else{ctx.fillStyle='#ff5ea8';ctx.beginPath();ctx.arc(x,y,hs*.72,0,7);ctx.fill();ctx.fillStyle='#151019';ctx.beginPath();ctx.arc(x-hs*.22,y-hs*.1,hs*.08,0,7);ctx.arc(x+hs*.22,y-hs*.1,hs*.08,0,7);ctx.fill()}ctx.restore()}
function rootOffset(p,state){let s=settings(),d=s.distance*(state.auto);let dx=$('direction').value==='left'?-d:$('direction').value==='up'?0:d,dy=$('direction').value==='up'?-d*.6:-Math.sin(performance.now()/600)*14;for(const q of Object.values(p.joints)){q.x+=dx;q.y+=dy}p.head.x+=dx;p.head.y+=dy;return p}
function loop(now){requestAnimationFrame(loop);let dt=now-lastFrame;lastFrame=now;fps=fps*.9+(1000/Math.max(1,dt))*.1;let s=settings(),f=audio.update(now,$('bpmAuto').checked);if(!$('bpmAuto').checked)audio.bpm=+$('bpm').value;let human=tracker.update(canvas.width,canvas.height,now)||lastPose||fallback(canvas.width,canvas.height,now);lastPose=human;let auto=dancePose(human,now,audio.bpm,s.genre,s.intensity,{bass:f.bass*s.reactivity,mid:f.mid,high:f.high});let state=performanceCtl.update(now),final=rootOffset(blend(human,auto,state.auto),state);ctx.clearRect(0,0,canvas.width,canvas.height);let mode=s.display;video.style.opacity=mode==='live'?'.7':mode==='silhouette'?'.16':'0';if(mode==='dark'||mode==='character')ctx.fillStyle='#07070a',ctx.fillRect(0,0,canvas.width,canvas.height);if(s.trail){trail.push(structuredClone(final));while(trail.length>18)trail.shift();trail.forEach((x,i)=>draw(x,(i/trail.length)*.17))}else trail=[];draw(final);if($('debug').checked){ctx.fillStyle='#fff';ctx.font='12px monospace';ctx.fillText(`ROOT ${Math.round(final.cx)} ${Math.round(final.cy)} · AUTO ${state.auto.toFixed(2)} · ${auto.phrase}`,20,canvas.height-20)}$('stats').textContent=`FPS ${fps.toFixed(0)} · BPM ${audio.bpm.toFixed(0)} · BEAT ${(Math.floor(now/(60000/audio.bpm))%4)+1} · ${performanceCtl.state} · ${auto.genre}`;$('notice').style.display=started?'none':'block'}requestAnimationFrame(loop);
$('camera').onclick=async()=>{try{let stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});video.srcObject=stream;await video.play();await tracker.start(video);started=true;$('camera').textContent='CAMERA ON'}catch(e){$('notice').textContent='Camera permission was not granted';console.error(e)}};
$('mic').onclick=async()=>{$('mic').textContent=await audio.start()?'MIC ON':'MIC UNAVAILABLE'};
$('faces').onchange=e=>{for(const file of e.target.files){let image=new Image();image.onload=()=>{faces.push(image);let o=document.createElement('option');o.value=faces.length-1;o.textContent=`FACE ${faces.length}`;$('faceSelect').append(o)};image.src=URL.createObjectURL(file)}};
['dragover','drop'].forEach(type=>$('panel').addEventListener(type,e=>{if(type==='dragover')e.preventDefault();else{$('faces').files=e.dataTransfer.files;$('faces').dispatchEvent(new Event('change'))}}));
document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{performanceCtl.set(b.dataset.state);if($('randomFace').checked&&faces.length)$('faceSelect').value=Math.floor(Math.random()*faces.length)});$('auto').onchange=e=>performanceCtl.auto=e.target.checked;$('bpm').oninput=e=>$('bpmOut').textContent=e.target.value;$('fullscreen').onclick=()=>document.documentElement.requestFullscreen();$('hide').onclick=()=>$('panel').classList.add('hidden');addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')$('panel').classList.toggle('hidden')});loop(performance.now());
