import{PoseTracker}from'./pose.js';import{AudioAnalyzer}from'./audio.js';import{PerformanceController}from'./performance.js';import{dancePose,blend}from'./dance.js';
const $=id=>document.getElementById(id),video=$('video'),canvas=$('canvas'),ctx=canvas.getContext('2d'),tracker=new PoseTracker(),audio=new AudioAnalyzer(),performanceCtl=new PerformanceController();let cameraOn=false,micOn=false,last=0,fps=0,trail=[];
const cfg=()=>({line:+$('line').value,intensity:+$('intensity').value,reactivity:+$('reactivity').value,distance:+$('distance').value,genre:$('genre').value,mirror:$('mirror').checked,display:$('display').value});function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener('resize',resize);resize();
const edge=[['shoulderL','shoulderR'],['shoulderL','elbowL'],['elbowL','wristL'],['shoulderR','elbowR'],['elbowR','wristR'],['shoulderL','hipL'],['shoulderR','hipR'],['hipL','hipR'],['hipL','kneeL'],['kneeL','ankleL'],['hipR','kneeR'],['kneeR','ankleR']];
function draw(p,a=1){let s=cfg(),j=p.joints;ctx.save();ctx.globalAlpha=a;ctx.strokeStyle='#d1ff45';ctx.shadowColor='#aaff00';ctx.shadowBlur=16;ctx.lineWidth=s.line;ctx.lineCap='round';for(const[x,y]of edge){ctx.beginPath();ctx.moveTo(j[x].x,j[x].y);ctx.lineTo(j[y].x,j[y].y);ctx.stroke()}ctx.shadowBlur=0;ctx.fillStyle='#fff';for(const q of Object.values(j)){ctx.beginPath();ctx.arc(q.x,q.y,Math.max(2,s.line*.4),0,7);ctx.fill()}ctx.fillStyle='#ff5ea8';ctx.beginPath();ctx.arc(p.head.x,p.head.y,p.scale*.5,0,7);ctx.fill();ctx.restore()}
function raw(p){if(!p)return;ctx.fillStyle='#ff5ea8';for(const q of p.rawLandmarks){ctx.beginPath();ctx.arc(q.x,q.y,2,0,7);ctx.fill()}}
function detach(p,x){let d=cfg().distance*x,dx=$('direction').value==='left'?-d:$('direction').value==='up'?0:d,dy=$('direction').value==='up'?-d*.6:0;for(const q of Object.values(p.joints)){q.x+=dx;q.y+=dy}p.head.x+=dx;p.head.y+=dy;return p}
function loop(now){requestAnimationFrame(loop);fps=fps*.9+1000/Math.max(1,now-last)*.1;last=now;let s=cfg(),f=audio.update(now,$('bpmAuto').checked);if(!$('bpmAuto').checked)audio.bpm=+$('bpm').value;video.style.transform=s.mirror?'scaleX(-1)':'none';let human=tracker.update(canvas.width,canvas.height,now,s.mirror),state=performanceCtl.update(now);ctx.clearRect(0,0,canvas.width,canvas.height);video.style.opacity=s.display==='live'?'.7':s.display==='silhouette'?'.16':'0';if(s.display==='dark'||s.display==='character'){ctx.fillStyle='#07070a';ctx.fillRect(0,0,canvas.width,canvas.height)}if(human){let p=performanceCtl.state==='FOLLOW'?human:detach(blend(human,dancePose(human,now,audio.bpm,s.genre,s.intensity,f),state.auto),state.auto);if(s.trail&&performanceCtl.state!=='FOLLOW'){trail.push(structuredClone(p));while(trail.length>18)trail.shift();trail.forEach((v,i)=>draw(v,i/trail.length*.16))}else trail=[];draw(p);if($('debug').checked)raw(tracker.raw)}else trail=[];$('notice').style.display=cameraOn&&!human?'block':'none';$('notice').textContent='NO POSE DETECTED';if($('debug').checked){ctx.fillStyle='#fff';ctx.font='12px monospace';ctx.fillText(`MediaPipe: ${tracker.status} | Camera: ${cameraOn?'ON':'OFF'} | Pose: ${human?'YES':'NO'} | confidence ${tracker.confidence.toFixed(2)} | landmarks ${tracker.landmarkCount} | Pose FPS ${tracker.poseFps.toFixed(0)}`,15,canvas.height-18)}$('stats').textContent=`FPS ${fps.toFixed(0)} · ${performanceCtl.state}`;$('bpmStatus').textContent=!micOn?'BPM: --':!$('bpmAuto').checked?`BPM: ${audio.bpm|0} (MANUAL)`:audio.last?`BPM: ${Math.round(audio.bpm)}`:'BPM: detecting...'}requestAnimationFrame(loop);
$('camera').onclick=async()=>{try{video.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'}});await video.play();cameraOn=await tracker.start(video);$('camera').textContent=cameraOn?'CAMERA ON':'CAMERA ERROR'}catch(e){console.error('[Camera]',e);cameraOn=false}};$('mic').onclick=async()=>{micOn=await audio.start();$('mic').textContent=micOn?'MIC ON':'MIC OFF'};$('bpm').oninput=e=>$('bpmOut').textContent=e.target.value;document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>performanceCtl.set(b.dataset.state));$('auto').onchange=e=>performanceCtl.auto=e.target.checked;$('fullscreen').onclick=()=>document.documentElement.requestFullscreen();$('hide').onclick=()=>$('panel').classList.add('hidden');addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')$('panel').classList.toggle('hidden')});loop(performance.now());
