const names=['shoulderL','shoulderR','elbowL','elbowR','wristL','wristR','hipL','hipR','kneeL','kneeR','ankleL','ankleR'];
const map={shoulderL:11,shoulderR:12,elbowL:13,elbowR:14,wristL:15,wristR:16,hipL:23,hipR:24,kneeL:25,kneeR:26,ankleL:27,ankleR:28};
export class PoseTracker {
 constructor(){this.landmarker=null;this.video=null;this.raw=null;this.smooth=null;this.status='IDLE';this.error='';this.poseFps=0;this.lastInfer=0;this.confidence=0;this.landmarkCount=0;}
 async start(video){this.video=video;this.status='LOADING';this.error='';try{const version='0.10.22';const {FilesetResolver,PoseLandmarker}=await import(`https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${version}`);const files=await FilesetResolver.forVisionTasks(`https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@${version}/wasm`);this.landmarker=await PoseLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task'},runningMode:'VIDEO',numPoses:1,minPoseDetectionConfidence:.5,minPosePresenceConfidence:.5,minTrackingConfidence:.5});this.status='READY';console.info('[Pose] MediaPipe ready');return true}catch(e){this.status='ERROR';this.error=String(e?.message||e);console.error('[Pose] MediaPipe initialization failed',e);return false}}
 update(w,h,now,mirror){if(!this.landmarker||!this.video||this.video.readyState<2||!this.video.videoWidth)return null;try{const result=this.landmarker.detectForVideo(this.video,now),l=result.landmarks?.[0];this.poseFps=this.lastInfer?this.poseFps*.85+1000/(now-this.lastInfer)*.15:0;this.lastInfer=now;if(!l){this.raw=null;this.smooth=null;this.confidence=0;this.landmarkCount=0;return null}this.confidence=l.reduce((sum,p)=>sum+(p.visibility??1),0)/l.length;this.landmarkCount=l.length;this.raw=this.fromLandmarks(l,w,h,mirror);this.smooth=this.smooth?this.ema(this.smooth,this.raw,.35):structuredClone(this.raw);return this.smooth}catch(e){this.status='ERROR';this.error=String(e?.message||e);console.error('[Pose] inference failed',e);return null}}
 fromLandmarks(l,w,h,mirror){const vw=this.video.videoWidth,vh=this.video.videoHeight,scale=Math.max(w/vw,h/vh),dw=vw*scale,dh=vh*scale,ox=(w-dw)/2,oy=(h-dh)/2,at=i=>({x:ox+(mirror?1-l[i].x:l[i].x)*dw,y:oy+l[i].y*dh});let joints={};for(const[k,i]of Object.entries(map))joints[k]=at(i);const cx=(joints.hipL.x+joints.hipR.x)/2,cy=(joints.hipL.y+joints.hipR.y)/2,bodyScale=Math.hypot(joints.shoulderL.x-joints.shoulderR.x,joints.shoulderL.y-joints.shoulderR.y);return {joints,cx,cy,scale:bodyScale,head:at(0),rawLandmarks:l.map((_,i)=>at(i))}}
 ema(a,b,k){let joints={};for(const n of names)joints[n]={x:a.joints[n].x+(b.joints[n].x-a.joints[n].x)*k,y:a.joints[n].y+(b.joints[n].y-a.joints[n].y)*k};return {...b,joints,cx:a.cx+(b.cx-a.cx)*k,cy:a.cy+(b.cy-a.cy)*k,scale:a.scale+(b.scale-a.scale)*k,head:{x:a.head.x+(b.head.x-a.head.x)*k,y:a.head.y+(b.head.y-a.head.y)*k}}}
}
